version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # To avoid overwriting node_modules from the container with the host's node_modules
    ports:
      - "3000:3000"
    command: yarn nx serve dice --watch
